<?php
/**
 * 360Contest
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    360contest
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class ContestTypeData {

	public $table = 'contest_types';

	public $records = array(
		array(
			'id' => '1',
			'resource_id' => '1',
			'name' => '99designs - Logo design',
			'description' => 'Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\'',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '15',
			'contest_user_count' => '0',
			'minimum_prize' => '10',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '40',
			'maximum_entries_allowed_per_user' => '0'
		),
		array(
			'id' => '2',
			'resource_id' => '1',
			'name' => '99designs - Business card design',
			'description' => 'dden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first t',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '11',
			'contest_user_count' => '0',
			'minimum_prize' => '10',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '0'
		),
		array(
			'id' => '3',
			'resource_id' => '1',
			'name' => '99designs - T-shirt design',
			'description' => 'This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '8',
			'contest_user_count' => '0',
			'minimum_prize' => '10',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '40',
			'maximum_entries_allowed_per_user' => '0'
		),
		array(
			'id' => '4',
			'resource_id' => '1',
			'name' => '99designs - Postcard or flyer design',
			'description' => 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form,',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '10',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '40',
			'maximum_entries_allowed_per_user' => '0'
		),
		array(
			'id' => '5',
			'resource_id' => '1',
			'name' => '99designs - Brochure design',
			'description' => 't here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum ',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '9',
			'contest_user_count' => '0',
			'minimum_prize' => '10',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '0'
		),
		array(
			'id' => '6',
			'resource_id' => '1',
			'name' => '99designs - Product packaging design',
			'description' => 't here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum ',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '10',
			'contest_user_count' => '0',
			'minimum_prize' => '10',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '0'
		),
		array(
			'id' => '8',
			'resource_id' => '1',
			'name' => '99designs - Banner Ad Design',
			'description' => 'But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '100',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '1'
		),
		array(
			'id' => '9',
			'resource_id' => '1',
			'name' => 'Design Contest - Logo Design',
			'description' => 'Design Contest - Logo Design',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '5',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '10',
			'resource_id' => '1',
			'name' => 'Design Contest - T-shirt Design',
			'description' => 'Design Contest - T-shirt Design',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '11',
			'resource_id' => '1',
			'name' => 'Design Contest - Banner Design',
			'description' => 'Design Contest - Banner Design',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '9',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '12',
			'resource_id' => '1',
			'name' => 'Design Contest - Website Desing',
			'description' => 'Design Contest - Website, Webpage or Landing Page Design',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '9',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '13',
			'resource_id' => '1',
			'name' => 'Design Contest - Mobile App Design',
			'description' => 'Design Contest - Mobile App Design',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '5',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '14',
			'resource_id' => '1',
			'name' => 'Creativeallies - Small Poster',
			'description' => 'Creativeallies - Small Poster',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '18',
			'resource_id' => '1',
			'name' => 'Hatchwise - Website',
			'description' => 'Hatchwise - Website',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '12',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '15',
			'resource_id' => '1',
			'name' => 'Creativeallies - Large Poster',
			'description' => 'Creativeallies - Large Poster',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '10',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '16',
			'resource_id' => '1',
			'name' => 'Creativeallies - T-shirt',
			'description' => 'Creativeallies - T-shirt',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '17',
			'resource_id' => '1',
			'name' => 'Hatchwise - Logo',
			'description' => 'Hatchwise - Logo',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '9',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '19',
			'resource_id' => '1',
			'name' => 'Hatchwise - T-shirt',
			'description' => 'Hatchwise - T-shirt',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '7',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '20',
			'resource_id' => '1',
			'name' => 'Hatchwise - Banner Ad',
			'description' => 'Hatchwise - Banner Ad',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '12',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '21',
			'resource_id' => '1',
			'name' => 'Logobids - Logo',
			'description' => 'Logobids - Logo',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '8',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '22',
			'resource_id' => '1',
			'name' => 'Logo Contest - Logo',
			'description' => 'Logo Contest - Logo',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '8',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '23',
			'resource_id' => '1',
			'name' => 'Logoarena - Logo',
			'description' => 'Logoarena - Logo',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '11',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '24',
			'resource_id' => '1',
			'name' => 'Design Crowd - Logo',
			'description' => 'Design Crowd - Logo',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '7',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '25',
			'resource_id' => '1',
			'name' => 'Design Crowd - Web',
			'description' => 'Design Crowd - Web',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '26',
			'resource_id' => '1',
			'name' => 'Design Crowd - Banner Ad',
			'description' => 'Design Crowd - Banner Ad',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '0',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '27',
			'resource_id' => '1',
			'name' => 'Design Crowd - Graphic',
			'description' => 'Design Crowd - Graphic',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '9',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '28',
			'resource_id' => '1',
			'name' => 'Design Crowd - App',
			'description' => 'Design Crowd - App',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '6',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
		array(
			'id' => '29',
			'resource_id' => '2',
			'name' => 'Wooshi',
			'description' => 'Wooshi',
			'next' => '',
			'contest_count' => '0',
			'form_field_count' => '5',
			'contest_user_count' => '0',
			'minimum_prize' => '70',
			'blind_fee' => '0',
			'private_fee' => '0',
			'featured_fee' => '0',
			'highlight_fee' => '0',
			'site_revenue' => '0',
			'is_watermarked' => '1',
			'is_active' => '1',
			'is_template' => '1',
			'is_blind' => '',
			'is_featured' => '',
			'is_highlight' => '',
			'is_private' => '',
			'maximum_entries_allowed' => '3',
			'maximum_entries_allowed_per_user' => '100'
		),
	);

}
