<?php
/**
 * 360Contest
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    360Contest
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class SettingData {

	public $table = 'settings';

	public $records = array(
		array(
			'id' => '1',
			'setting_category_id' => '21',
			'setting_category_parent_id' => '1',
			'name' => 'site.name',
			'value' => '360Contest',
			'description' => 'This name will be used in all pages, emails.',
			'type' => 'text',
			'options' => '',
			'label' => 'Name',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '2',
			'setting_category_id' => '22',
			'setting_category_parent_id' => '1',
			'name' => 'EmailTemplate.admin_email',
			'value' => '',
			'description' => 'This is the email address to which you will receive the mail from contact form.',
			'type' => 'text',
			'options' => '',
			'label' => 'Contact Email Address',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '3',
			'setting_category_id' => '22',
			'setting_category_parent_id' => '1',
			'name' => 'EmailTemplate.from_email',
			'value' => '',
			'description' => 'This is the email address that will appear in the \"From\" field of all emails sent from the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'From Email Address',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '4',
			'setting_category_id' => '22',
			'setting_category_parent_id' => '1',
			'name' => 'EmailTemplate.reply_to_email',
			'value' => '',
			'description' => '\"Reply-To\" email header for all emails. Leave it empty to receive replies as usual (to \"From\" email address).',
			'type' => 'text',
			'options' => '',
			'label' => 'Reply to Email Address',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '269',
			'setting_category_id' => '72',
			'setting_category_parent_id' => '15',
			'name' => 'google.consumer_key',
			'value' => '',
			'description' => 'This is the Client ID used in Gmail share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Client ID',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '268',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.username',
			'value' => 'agriyacontest',
			'description' => 'This is the Twitter username of the account has been created.',
			'type' => 'text',
			'options' => '',
			'label' => 'Twitter Username',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '16',
			'setting_category_id' => '23',
			'setting_category_parent_id' => '2',
			'name' => 'site.maintenance_mode',
			'value' => '0',
			'description' => 'On enabling this feature, only administrator can access the site (e.g., http://yourdomain.com/admin). Users will see a temporary page until you return to turn this off. (Turn this on, whenever you need to perform maintenance in the site.)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Maintenance Mode',
			'order' => '16',
			'plugin_name' => ''
		),
		array(
			'id' => '21',
			'setting_category_id' => '24',
			'setting_category_parent_id' => '3',
			'name' => 'meta.keywords',
			'value' => 'crowd, design, contest',
			'description' => 'These are the keywords used for improving search engine results of our site. (Comma separated for multiple keywords.)',
			'type' => 'text',
			'options' => '',
			'label' => 'Keywords',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '22',
			'setting_category_id' => '24',
			'setting_category_parent_id' => '3',
			'name' => 'meta.description',
			'value' => '360Contest',
			'description' => 'This is the short description of your site, used by search engines on search result pages to display preview snippets for a given page.',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Description',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '23',
			'setting_category_id' => '25',
			'setting_category_parent_id' => '3',
			'name' => 'site.tracking_script',
			'value' => '<script type=\"text/javascript\"> var _gaq = _gaq || []; _gaq.push([\'_setAccount\', \'UA-4819298-1\']); _gaq.push([\'_setDomainName\', \'burrow.dev.agriya.com\']); _gaq.push([\'_trackPageview\']); (function() { var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true; ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\'; var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s); })(); </script>',
			'description' => 'This is the site tracker script, used for track and analyze data about how people are getting to your website. e.g., Google Analytics. <a href=\"http://www.google.com/analytics/\">http://www.google.com/analytics/</a>',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Site Tracker Code',
			'order' => '15',
			'plugin_name' => ''
		),
		array(
			'id' => '24',
			'setting_category_id' => '25',
			'setting_category_parent_id' => '3',
			'name' => 'site.robots',
			'value' => '',
			'description' => 'Content for robots.txt; (search engine) robots specific instructions. Refer,<a href=\"http://www.robotstxt.org/\">http://www.robotstxt.org/</a> for syntax and usage.',
			'type' => 'textarea',
			'options' => '',
			'label' => 'robots.txt',
			'order' => '17',
			'plugin_name' => ''
		),
		array(
			'id' => '31',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.date.format',
			'value' => '%b %d, %Y',
			'description' => 'This is the date format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date Format',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '32',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.datetime.format',
			'value' => '%b %d, %Y %I:%M %p',
			'description' => 'This is the date-time format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date-Time Format',
			'order' => '12',
			'plugin_name' => ''
		),
		array(
			'id' => '33',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.time.format',
			'value' => '%I:%M %p',
			'description' => 'This is the time format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Time Format',
			'order' => '10',
			'plugin_name' => ''
		),
		array(
			'id' => '34',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.date.tooltip',
			'value' => '%b %d, %Y %I:%M %p',
			'description' => 'This is the date tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date Tooltip Format',
			'order' => '8',
			'plugin_name' => ''
		),
		array(
			'id' => '35',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.time.tooltip',
			'value' => '%B %d, %Y (%A) %Z',
			'description' => 'This is the time tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Time Tooltip Format',
			'order' => '11',
			'plugin_name' => ''
		),
		array(
			'id' => '36',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.datetime.tooltip',
			'value' => '%B %d, %Y %I:%M:%S %p (%A) %Z',
			'description' => 'This is the date-time tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date-Time Tooltip Format',
			'order' => '13',
			'plugin_name' => ''
		),
		array(
			'id' => '37',
			'setting_category_id' => '26',
			'setting_category_parent_id' => '4',
			'name' => 'site.language',
			'value' => 'en',
			'description' => 'The selected language will be used as default language all over the site (also for emails)',
			'type' => 'select',
			'options' => '',
			'label' => 'Site Language',
			'order' => '3',
			'plugin_name' => 'Translation'
		),
		array(
			'id' => '38',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '4',
			'name' => 'site.currency_symbol_place',
			'value' => 'left',
			'description' => 'The selected position will be used as default currency symbol position all over the site (also for emails)',
			'type' => 'select',
			'options' => 'left,right',
			'label' => 'Currency Symbol Position',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '39',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '4',
			'name' => 'site.currency_code',
			'value' => 'USD',
			'description' => 'PayPal doesn\'t support all currencies; refer, <a href=\"https://www.paypal.com/cgi-bin/webscr?cmd=p/sell/mc/mc_wa-outside\" target=\"_blank\">PayPal documentation</a> for list of supported currencies. Please use supported currency code. Also, your PayPal account must set to accept the specified currency. Please follow the ##PAYPAL_INSTRUCTION##, if not done already.',
			'type' => 'select',
			'options' => 'AUD,BRL,CAD,CZK,DKK,EUR,HKD,HUF,ILS,JPY,MXN,NOK,NZD,PHP,PLN,GBP,SGD,SEK,CHF,TWD,THB,USD',
			'label' => 'Default Transaction Currency',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '40',
			'setting_category_id' => '27',
			'setting_category_parent_id' => '4',
			'name' => 'site.datetimehighlight.tooltip',
			'value' => '%B %d, %Y %I:%M:%S %p (%A) %Z',
			'description' => 'This is the date-time-hilight tooltip format which is displayed in our site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Date-Time-Hilight Tooltip Format',
			'order' => '14',
			'plugin_name' => ''
		),
		array(
			'id' => '51',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'user.using_to_login',
			'value' => 'username',
			'description' => 'Users will be able to login with chosen login handle (username or email address) along with their password.',
			'type' => 'select',
			'options' => 'username, email',
			'label' => 'Login Handle',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '52',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_admin_activate_after_register',
			'value' => '0',
			'description' => 'On enabling this feature, admin need to approve each user after registration (User cannot login until admin approves)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Administrator Approval After Registration',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '53',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_email_verification_for_register',
			'value' => '1',
			'description' => 'On enabling this feature, user need to verify their email address provided during registration. (User cannot login until email address is verified)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Email Verification After Registration',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '54',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_auto_login_after_register',
			'value' => '0',
			'description' => 'On enabling this feature, users will be automatically logged-in after registration. (Only when \"Email Verification\" & \"Admin Approval\" is disabled)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Login After Registration',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '55',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_admin_mail_after_register',
			'value' => '1',
			'description' => 'On enabling this feature, notification mail will be sent to administrator on each registration.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Notify Administrator on Each Registration',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '56',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_welcome_mail_after_register',
			'value' => '1',
			'description' => 'On enabling this feature, users will receive a welcome mail after registration.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Sending Welcome Mail After Registration',
			'order' => '7',
			'plugin_name' => ''
		),
		array(
			'id' => '57',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_logout_after_change_password',
			'value' => '1',
			'description' => 'On enabling this feature, users will be asked to log-in again.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto-Logout After Password Change',
			'order' => '8',
			'plugin_name' => ''
		),
		array(
			'id' => '290',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.medium_small_thumb.width',
			'value' => '45',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '291',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.medium_small_thumb.height',
			'value' => '44',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '59',
			'setting_category_id' => '31',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_allow_user_to_switch_language',
			'value' => '1',
			'description' => 'On enabling this feature, users can change site language to their choice.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable User to Switch Language',
			'order' => '14',
			'plugin_name' => 'Translation'
		),
		array(
			'id' => '60',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'facebook.is_enabled_facebook_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their site account using Facebook.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Facebook',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '61',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'twitter.is_enabled_twitter_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their site account using Twitter.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Twitter',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '71',
			'setting_category_id' => '33',
			'setting_category_parent_id' => '7',
			'name' => 'user.minimum_withdraw_amount',
			'value' => '2',
			'description' => 'This is the minimum amount a user can withdraw from their wallet.',
			'type' => 'text',
			'options' => '',
			'label' => 'Minimum Wallet Withdrawal Amount',
			'order' => '1',
			'plugin_name' => 'Withdrawals'
		),
		array(
			'id' => '72',
			'setting_category_id' => '33',
			'setting_category_parent_id' => '7',
			'name' => 'user.maximum_withdraw_amount',
			'value' => '100',
			'description' => 'This is the maximum amount a user can withdraw from their wallet.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Wallet Withdrawal Amount',
			'order' => '2',
			'plugin_name' => 'Withdrawals'
		),
		array(
			'id' => '73',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '6',
			'name' => 'wallet.min_wallet_amount',
			'value' => '10',
			'description' => 'This is the minimum amount a user can add to his wallet.',
			'type' => 'text',
			'options' => '',
			'label' => 'Minimum Wallet Funding Limit',
			'order' => '5',
			'plugin_name' => 'Wallet'
		),
		array(
			'id' => '74',
			'setting_category_id' => '32',
			'setting_category_parent_id' => '6',
			'name' => 'wallet.max_wallet_amount',
			'value' => '2000',
			'description' => 'This is the maximum amount a user can add to his wallet. (If left empty, then, no maximum amount restrictions)',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Wallet Funding Limit',
			'order' => '6',
			'plugin_name' => 'Wallet'
		),
		array(
			'id' => '86',
			'setting_category_id' => '36',
			'setting_category_parent_id' => '8',
			'name' => 'Watermark.watermark_text',
			'value' => '360Contest',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Watermark Text',
			'order' => '4',
			'plugin_name' => 'ImageResources'
		),
		array(
			'id' => '234',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.discusion_thumb.width',
			'value' => '45',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '88',
			'setting_category_id' => '36',
			'setting_category_parent_id' => '8',
			'name' => 'Watermark.watermark_possition_y',
			'value' => '73',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Y Position of Watermark',
			'order' => '6',
			'plugin_name' => 'ImageResources'
		),
		array(
			'id' => '90',
			'setting_category_id' => '36',
			'setting_category_parent_id' => '8',
			'name' => 'Watermark.watermark_possition_x',
			'value' => '30',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'X Position of Watermark',
			'order' => '5',
			'plugin_name' => 'ImageResources'
		),
		array(
			'id' => '92',
			'setting_category_id' => '36',
			'setting_category_parent_id' => '8',
			'name' => 'site.watermark',
			'value' => 'logo.png',
			'description' => 'Upload JPG, PNG or GIF image to be used as watermark. PNG images with transparency give the best results.',
			'type' => 'file',
			'options' => '',
			'label' => 'Watermark Image',
			'order' => '2',
			'plugin_name' => 'ImageResources'
		),
		array(
			'id' => '93',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.contest_type_minimum_prize',
			'value' => '70',
			'description' => 'This is global minimum prize amount. It can be overridden per contest type.',
			'type' => 'text',
			'options' => '',
			'label' => 'Contest Type Minimum Prize Amount',
			'order' => '5',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '136',
			'setting_category_id' => '41',
			'setting_category_parent_id' => '11',
			'name' => 'suspicious_detector.is_enabled',
			'value' => '1',
			'description' => 'On enabling this feature, system will check user inputs given in contests, contest comments and messages.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Suspicious Word Detector',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '137',
			'setting_category_id' => '41',
			'setting_category_parent_id' => '11',
			'name' => 'suspicious_detector.suspiciouswords',
			'value' => 'stupid
fool
\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*([,;]\\s*\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*)*
(?:\\+?1)?[-\\/. ]?[2-9][0-8][0-9][-\\/. ]?[2-9][0-9]{2}[-\\/. ]?[0-9]{4}',
			'description' => 'The suspicious words given will be matched with user given message and will be auto flagged if such words are found. (Note: Suspicious detection will be checked during contest creation & send message. Detection words should be newline separated.)',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Suspicious Words',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '138',
			'setting_category_id' => '42',
			'setting_category_parent_id' => '11',
			'name' => 'suspicious_detector.auto_suspend_contest_on_system_flag',
			'value' => '1',
			'description' => 'Auto suspended contests will not display in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Suspend Contest on System Flag',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '139',
			'setting_category_id' => '42',
			'setting_category_parent_id' => '11',
			'name' => 'suspicious_detector.auto_suspend_message_on_system_flag',
			'value' => '1',
			'description' => 'Auto suspended message will not display in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Suspend Message on System Flag',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '146',
			'setting_category_id' => '43',
			'setting_category_parent_id' => '12',
			'name' => 'messages.is_send_email_on_new_message',
			'value' => '1',
			'description' => 'On enabling this feature, users will be notified by an email for every new message.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Notify via Mail on New Message',
			'order' => '5',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '147',
			'setting_category_id' => '43',
			'setting_category_parent_id' => '12',
			'name' => 'messages.is_allow_send_messsage',
			'value' => '1',
			'description' => 'On disabling this feature, user cannot able to send message to other user in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Send Message Option',
			'order' => '3',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '148',
			'setting_category_id' => '43',
			'setting_category_parent_id' => '12',
			'name' => 'messages.thread_max_depth',
			'value' => '3',
			'description' => '0 for unlimited. Below this thread level \"Reply\" option will not be available. This is to avoid broken design due to thread level.',
			'type' => 'text',
			'options' => '',
			'label' => 'Thread Maximum Depth',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '149',
			'setting_category_id' => '43',
			'setting_category_parent_id' => '12',
			'name' => 'messages.allow_all_users_to_comment_upto_status',
			'value' => 'Open',
			'description' => 'All user to comment up to selected level',
			'type' => 'select',
			'options' => 'Open,Judging,WinnerSelected,Completed',
			'label' => 'All user to comment up to limited level',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '156',
			'setting_category_id' => '44',
			'setting_category_parent_id' => '13',
			'name' => 'cdn.js',
			'value' => '',
			'description' => 'This is base URL (including trailing slash) for CDN JavaScript. (e.g., http://js.yourdomain.com/)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN JS URL',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '157',
			'setting_category_id' => '44',
			'setting_category_parent_id' => '13',
			'name' => 'cdn.css',
			'value' => '',
			'description' => 'This is base URL (including trailing slash) for CDN CSS. (e.g., http://css.yourdomain.com/)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN CSS URL',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '158',
			'setting_category_id' => '44',
			'setting_category_parent_id' => '13',
			'name' => 'cdn.images',
			'value' => '',
			'description' => 'This is base URL (including trailing slash) for CDN images. (e.g., http://images.yourdomain.com/)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN Image URL',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '167',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.fb_secrect_key',
			'value' => '',
			'description' => 'This is the Facebook secret key used for authentication and other Facebook related plugins support',
			'type' => 'text',
			'options' => '',
			'label' => 'App Secret',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '168',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.consumer_key',
			'value' => '',
			'description' => 'This is the consumer key used for authentication and posting on Twitter.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Key',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '169',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.consumer_secret',
			'value' => '',
			'description' => 'This is the consumer secret key used for authentication and posting on Twitter.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer secret',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '170',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.fb_app_id',
			'value' => '',
			'description' => 'This is the application ID used in login and post.',
			'type' => 'text',
			'options' => '',
			'label' => 'App ID',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '171',
			'setting_category_id' => '50',
			'setting_category_parent_id' => '15',
			'name' => 'google.translation_api_key',
			'value' => '',
			'description' => 'This is the configured Google Translate API key.',
			'type' => 'text',
			'options' => '',
			'label' => 'API Key',
			'order' => '0',
			'plugin_name' => 'Translation'
		),
		array(
			'id' => '172',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.site_twitter_url',
			'value' => '',
			'description' => 'This is the site Twitter URL used for displaying in the footer.',
			'type' => 'text',
			'options' => '',
			'label' => 'Twitter Account URL',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '174',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.site_facebook_url',
			'value' => 'http://www.facebook.com/360Contest',
			'description' => 'This is the site Facebook URL used to display in the footer',
			'type' => 'text',
			'options' => '',
			'label' => 'Facebook Account URL',
			'order' => '7',
			'plugin_name' => ''
		),
		array(
			'id' => '175',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.fb_access_token',
			'value' => '',
			'description' => 'This will be automatically updated when \"Update Facebook Credentials\" link is clicked. (Required for posting in Facebook)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Token',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '176',
			'setting_category_id' => '48',
			'setting_category_parent_id' => '15',
			'name' => 'facebook.fb_user_id',
			'value' => '',
			'description' => 'This will be automatically updated when \"Update Facebook Credentials\" link is clicked. (Required for posting in Facebook)',
			'type' => 'text',
			'options' => '',
			'label' => 'User ID',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '177',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.site_user_access_key',
			'value' => '',
			'description' => 'This will be automatically updated when  \"Update Twitter Credentials\" link is clicked. 
(Required for posting in Twitter)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access token secret',
			'order' => '3',
			'plugin_name' => ''
		),
		array(
			'id' => '178',
			'setting_category_id' => '49',
			'setting_category_parent_id' => '15',
			'name' => 'twitter.site_user_access_token',
			'value' => '',
			'description' => 'This will be automatically updated when  \"Update Twitter Credentials\" link is clicked. 
(Required for posting in Twitter)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Token',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '245',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.blind_fee',
			'value' => '70',
			'description' => 'This is blind fee for the contest. It can be overridden per contest type.',
			'type' => 'text',
			'options' => '',
			'label' => 'Blind Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '246',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.private_fee',
			'value' => '80',
			'description' => 'This is private fee for the contest. It can be overridden per contest type.',
			'type' => 'text',
			'options' => '',
			'label' => 'Private Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '180',
			'setting_category_id' => '28',
			'setting_category_parent_id' => '4',
			'name' => 'site.currency',
			'value' => '$',
			'description' => 'Currency for the site',
			'type' => 'text',
			'options' => '',
			'label' => 'Site Currency',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '150',
			'setting_category_id' => '43',
			'setting_category_parent_id' => '12',
			'name' => 'message.is_send_external_message',
			'value' => '1',
			'description' => 'Allow users to receive external message. (users registered email address)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Send external message',
			'order' => '2',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '151',
			'setting_category_id' => '43',
			'setting_category_parent_id' => '12',
			'name' => 'message.is_send_interal_message',
			'value' => '1',
			'description' => 'Allow users to receive internal message
(Disabling this will also disable the external message sending internally.)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Send internal message',
			'order' => '1',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '196',
			'setting_category_id' => '56',
			'setting_category_parent_id' => '9',
			'name' => 'user.signup_fee',
			'value' => '0',
			'description' => 'Setting the value empty or zero will leads to no membership fee',
			'type' => 'text',
			'options' => '',
			'label' => 'User Membership Fee',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '199',
			'setting_category_id' => '23',
			'setting_category_parent_id' => '2',
			'name' => 'site.look_up_url',
			'value' => 'http://whois.sc/',
			'description' => 'URL prefix
for whois lookup service. Will be used in whois links found in
##USER_LOGIN## pages to resolve users\' IP to where they are
from&mdash;often down to the city or neighborhood or country. This is
a security feature.',
			'type' => 'text',
			'options' => '',
			'label' => 'Whois Lookup URL',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '95',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.winner_commission_amount',
			'value' => '10',
			'description' => 'Site fee/commission in percentage to be taken from contest winner. It can be overridden per contest type. Contest winner will get Prize amount - Site fee.',
			'type' => 'text',
			'options' => '',
			'label' => 'Site Commission Percentage from Contest Winner',
			'order' => '6',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '200',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'Hook.bootstraps',
			'value' => 'Contests,ContestFlags,ContestFollowers,UserFlags,UserFavourites,EntryFlags,EntryRatings,Wallet,Withdrawals,Translation',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '201',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'site.theme',
			'value' => '',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '202',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'messages.content_length',
			'value' => '40',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '203',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'messages.page_size',
			'value' => '50',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '204',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'site.version',
			'value' => 'v2.0b3',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '205',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.big_thumb.height',
			'value' => '100',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '206',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.big_thumb.width',
			'value' => '100',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '209',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.medium_thumb.height',
			'value' => '50',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '210',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.medium_thumb.width',
			'value' => '50',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '211',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.micro_thumb.height',
			'value' => '18',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '212',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.micro_thumb.width',
			'value' => '18',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '213',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.normal_thumb.height',
			'value' => '45',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '214',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.normal_thumb.width',
			'value' => '45',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '215',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.small_big_thumb.height',
			'value' => '155',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '216',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.small_big_thumb.width',
			'value' => '155',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '217',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.small_thumb.height',
			'value' => '30',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '218',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.small_thumb.width',
			'value' => '30',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '219',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.very_big_thumb.height',
			'value' => '600',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '220',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.very_big_thumb.width',
			'value' => '600',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '222',
			'setting_category_id' => '58',
			'setting_category_parent_id' => '8',
			'name' => 'contest.judging_to_winner_selected_days',
			'value' => '1000',
			'description' => 'Contest will move to \"Pending Action to Admin\", when contest holder
doesn\'t select winner before mentioned days. In that case, Admin will
be forced to select winner.',
			'type' => 'text',
			'options' => '',
			'label' => 'From Judging Status',
			'order' => '8',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '223',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_auto_approve',
			'value' => '1',
			'description' => 'On enabling this feature, posted contest will immediately get listed. (Contest will not wait for admin approval)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Approval After New Contest',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '224',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.slider_thumb.height',
			'value' => '52',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '225',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.slider_thumb.width',
			'value' => '68',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '226',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.entry_big_thumb.height',
			'value' => '287',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '227',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.entry_big_thumb.width',
			'value' => '382',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '230',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'ContestUser.is_handle_aspect',
			'value' => '1',
			'description' => 'Aspect ratio is allowed or not',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Handle aspect ratio?',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '233',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.discusion_thumb.height',
			'value' => '45',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '231',
			'setting_category_id' => '36',
			'setting_category_parent_id' => '8',
			'name' => 'ContestUser.watermark_type',
			'value' => 'Watermark Image',
			'description' => 'By selecting the water mark type can be changed',
			'type' => 'radio',
			'options' => 'Watermark Image,Enable Text Watermark',
			'label' => 'Watermark Type',
			'order' => '0',
			'plugin_name' => 'ImageResources'
		),
		array(
			'id' => '232',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'ContestUser.request_refund_entry_limit',
			'value' => '1',
			'description' => 'Enable Request for Cancellation option only when the entries count is less than or equal to this value. Leave empty for no limit.',
			'type' => 'text',
			'options' => '',
			'label' => 'Entries Limit Required to Enable Request for Cancellation',
			'order' => '2',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '236',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.enable_request_for_cancellation',
			'value' => '1',
			'description' => 'On enabling this feature, user have request refund option in the judging status. Note: Initial Site Fee won\'t be refunded. Authorized prize amount will be voided.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable \"Request for Cancellation\" for Contest Holder',
			'order' => '1',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '237',
			'setting_category_id' => '58',
			'setting_category_parent_id' => '8',
			'name' => 'contest.contest_payment_pending_days_limit',
			'value' => '1000',
			'description' => 'If Contest Holder doesn\'t pay in above mentioned days, contest will be deleted.The process that could happen during the cron run.',
			'type' => 'text',
			'options' => '',
			'label' => 'Payment for Contest',
			'order' => '7',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '238',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.maximum_entry_allowed',
			'value' => '25',
			'description' => 'This is global maximum allowed entry per contest. It can be overridden per contest type.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Entries Allowed per Contest',
			'order' => '3',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '239',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.maximum_entry_allowed_per_user',
			'value' => '10',
			'description' => 'This is global maximum allowed entry per user. It can be overridden per contest type.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Entries Allowed per User per Contest',
			'order' => '4',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '240',
			'setting_category_id' => '58',
			'setting_category_parent_id' => '8',
			'name' => 'contest.winner_selected_to_completed_days',
			'value' => '1000',
			'description' => 'Contest will move to \"Pending Action to Admin\", when contest holder doesn\'t request any change in entry or mark as completed before mentioned days. In that case, Admin will be forced to complete contest.',
			'type' => 'text',
			'options' => '',
			'label' => 'From Winner Selected Status',
			'order' => '9',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '241',
			'setting_category_id' => '58',
			'setting_category_parent_id' => '8',
			'name' => 'contest.change_completed_to_completed_days',
			'value' => '1000',
			'description' => 'Contest will move to \"Pending Action to Admin\", when contest holder doesn\'t request any new change in entry or mark as completed before mentioned days. In that case, Admin will be forced to complete contest.',
			'type' => 'text',
			'options' => '',
			'label' => 'From Change Completed Status',
			'order' => '10',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '242',
			'setting_category_id' => '56',
			'setting_category_parent_id' => '9',
			'name' => 'user.signup_fee_payer',
			'value' => 'User',
			'description' => '',
			'type' => 'radio',
			'options' => 'User,Site',
			'label' => 'Who will pay the gateway fee for signup',
			'order' => '2',
			'plugin_name' => 'Sudopay'
		),
		array(
			'id' => '243',
			'setting_category_id' => '60',
			'setting_category_parent_id' => '9',
			'name' => 'wallet.wallet_fee_payer',
			'value' => 'User',
			'description' => '',
			'type' => 'radio',
			'options' => 'User,Site',
			'label' => 'Who will pay the gateway fee for wallet',
			'order' => '0',
			'plugin_name' => 'Sudopay'
		),
		array(
			'id' => '244',
			'setting_category_id' => '42',
			'setting_category_parent_id' => '11',
			'name' => 'suspicious_detector.auto_suspend_contest_user_on_system_flag',
			'value' => '1',
			'description' => 'Auto suspended entry will not display in site.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Auto Suspend Entry on System Flag',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '247',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.featured_fee',
			'value' => '100',
			'description' => 'This is featured fee for the contest. It can be overridden per contest type.',
			'type' => 'text',
			'options' => '',
			'label' => 'Featured Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '248',
			'setting_category_id' => '61',
			'setting_category_parent_id' => '15',
			'name' => 'captcha.challenge_key',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Challenge Key',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '249',
			'setting_category_id' => '61',
			'setting_category_parent_id' => '15',
			'name' => 'captcha.verification_key',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Verification Key',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '250',
			'setting_category_id' => '61',
			'setting_category_parent_id' => '15',
			'name' => 'captcha.hash_key',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Authentication Hash Key',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '251',
			'setting_category_id' => '63',
			'setting_category_parent_id' => '62',
			'name' => 'widget.footer_script',
			'value' => ' <img src=\"http://placehold.it/728X90\" alt =\"728X90\" width=\"728\" height=\"90\"  />',
			'description' => 'This is the footer script, used for display banners in footer',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '252',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contestuser.file.allowedSize',
			'value' => '9',
			'description' => 'By changing this value entry image size allowed will changed. ',
			'type' => 'text',
			'options' => '',
			'label' => 'Entry Image size',
			'order' => '0',
			'plugin_name' => 'ImageResources'
		),
		array(
			'id' => '253',
			'setting_category_id' => '64',
			'setting_category_parent_id' => '1',
			'name' => 'system.captcha_type',
			'value' => 'Solve Media',
			'description' => 'By changing this settings the captcha type will be changed in the user side.',
			'type' => 'radio',
			'options' => 'Basic,Solve Media',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '254',
			'setting_category_id' => '65',
			'setting_category_parent_id' => '62',
			'name' => 'widget.home_script',
			'value' => '',
			'description' => 'This is the home page script, used for display banners in home page',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '255',
			'setting_category_id' => '66',
			'setting_category_parent_id' => '62',
			'name' => 'widget.contest_script',
			'value' => '',
			'description' => 'This is the contest page script, used for display banners in contest page',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '256',
			'setting_category_id' => '67',
			'setting_category_parent_id' => '62',
			'name' => 'widget.user_script',
			'value' => ' <img src=\"http://placehold.it/468X60\" alt =\"468X60\" width=\"468\" height=\"60\"  />',
			'description' => 'This is the user page script, used for display banners in user page',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Code',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '257',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.iphone_medium_thumb.width',
			'value' => '54',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '258',
			'setting_category_id' => '68',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.iphone_medium_thumb.height',
			'value' => '49',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '259',
			'setting_category_id' => '68',
			'setting_category_parent_id' => '68',
			'name' => 'site.iphone_app_key',
			'value' => '',
			'description' => 'This is the security key used for iPhone App',
			'type' => 'text',
			'options' => '',
			'label' => 'App key',
			'order' => '1',
			'plugin_name' => ''
		),
		array(
			'id' => '260',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.contest_holder_alt_name_singular_small',
			'value' => 'contest holder',
			'description' => 'Singular lower case alternate name for contest holder which will be displayed throughout the site.',
			'type' => 'text',
			'options' => 'NULL',
			'label' => 'Contest Holder - Lower case, Singular - contest holder',
			'order' => '1',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '261',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.contest_holder_alt_name_singular_caps',
			'value' => 'Contest Holder',
			'description' => 'Singular title case alternate name for contest holder which will be displayed throughout the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Contest Holder - Title case, Singular - Contest Holder',
			'order' => '2',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '262',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.contest_holder_alt_name_plural_small',
			'value' => 'contest holders',
			'description' => 'Plural lower case alternate name for contest holder which will be displayed throughout the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Contest Holder - Lower case, Plural - contest holders',
			'order' => '3',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '263',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.contest_holder_alt_name_plural_caps',
			'value' => 'Contest Holders',
			'description' => 'Plural title case alternate name for contest holder which will be displayed throughout the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Contest Holder - Title case, Plural - Contest Holders',
			'order' => '4',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '264',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.participant_alt_name_singular_small',
			'value' => 'participant',
			'description' => 'Singular lower case alternate name for participant which will be displayed throughout the site.',
			'type' => 'text',
			'options' => 'NULL',
			'label' => 'Participant - Lower case, Singular - participant',
			'order' => '5',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '265',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.participant_alt_name_singular_caps',
			'value' => 'Participant',
			'description' => 'Singular title case alternate name for participant which will be displayed throughout the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Participant - Title case, Singular -Participant',
			'order' => '6',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '266',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.participant_alt_name_plural_small',
			'value' => 'participants',
			'description' => 'Plural lower case alternate name for participant which will be displayed throughout the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Participant - Lower case, Plural - participants',
			'order' => '7',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '267',
			'setting_category_id' => '54',
			'setting_category_parent_id' => '8',
			'name' => 'contest.participant_alt_name_plural_caps',
			'value' => 'Participants',
			'description' => 'Plural title case alternate name for participant which will be displayed throughout the site.',
			'type' => 'text',
			'options' => '',
			'label' => 'Participant - Title case, Plural - Participants',
			'order' => '8',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '270',
			'setting_category_id' => '72',
			'setting_category_parent_id' => '15',
			'name' => 'google.consumer_secret',
			'value' => '',
			'description' => 'This is the Secrete key used in Gmail share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Client Secret',
			'order' => '7',
			'plugin_name' => ''
		),
		array(
			'id' => '271',
			'setting_category_id' => '73',
			'setting_category_parent_id' => '15',
			'name' => 'yahoo.consumer_key',
			'value' => '',
			'description' => 'This is the Consumer Key is used in Yahoo! share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Key',
			'order' => '8',
			'plugin_name' => ''
		),
		array(
			'id' => '272',
			'setting_category_id' => '73',
			'setting_category_parent_id' => '15',
			'name' => 'yahoo.consumer_secret',
			'value' => '',
			'description' => 'This is the Consumer Secret Key is used in Yahoo! share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer Secret',
			'order' => '9',
			'plugin_name' => ''
		),
		array(
			'id' => '273',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '15',
			'name' => 'linkedin.consumer_key',
			'value' => '',
			'description' => 'This is the Consumer Key used in LinkedIn share.',
			'type' => 'text',
			'options' => '',
			'label' => 'API Key',
			'order' => '10',
			'plugin_name' => ''
		),
		array(
			'id' => '274',
			'setting_category_id' => '74',
			'setting_category_parent_id' => '15',
			'name' => 'linkedin.consumer_secret',
			'value' => '',
			'description' => 'This is the Secret Key used in LinkedIn share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Secret Key',
			'order' => '10',
			'plugin_name' => ''
		),
		array(
			'id' => '275',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'openid.is_enabled_openid_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their 360Contest account using OpenID.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable OpenID',
			'order' => '5',
			'plugin_name' => ''
		),
		array(
			'id' => '276',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'google.is_enabled_google_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their 360Contest account using Google.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Google',
			'order' => '6',
			'plugin_name' => ''
		),
		array(
			'id' => '277',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'yahoo.is_enabled_yahoo_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their 360Contest account using Yahoo!.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Yahoo!',
			'order' => '7',
			'plugin_name' => ''
		),
		array(
			'id' => '278',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'linkedin.is_enabled_linkedin_connect',
			'value' => '1',
			'description' => 'On enabling this feature, users can authenticate their 360Contest account using Linkedin.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Linkedin',
			'order' => '8',
			'plugin_name' => ''
		),
		array(
			'id' => '279',
			'setting_category_id' => '70',
			'setting_category_parent_id' => '69',
			'name' => 'invite.facebook',
			'value' => 'Check out this website ##SITE_NAME## ##REFERRAL_URL##',
			'description' => '',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Invite Facebook Content',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '280',
			'setting_category_id' => '70',
			'setting_category_parent_id' => '69',
			'name' => 'invite.twitter',
			'value' => 'Check out this website ##SITE_NAME## ##REFERRAL_URL##',
			'description' => '',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Invite Twitter Content',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '281',
			'setting_category_id' => '71',
			'setting_category_parent_id' => '69',
			'name' => 'share.facebook',
			'value' => 'Check out this website ##SITE_NAME## ##SHARE_URL##',
			'description' => '',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Facebook Share content',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '282',
			'setting_category_id' => '71',
			'setting_category_parent_id' => '69',
			'name' => 'share.twitter',
			'value' => 'Check out this contest ##CONTEST_NAME##',
			'description' => '',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Twitter Share content',
			'order' => '0',
			'plugin_name' => 'SocialMarketing'
		),
		array(
			'id' => '283',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_enable_blind_fee',
			'value' => '1',
			'description' => 'On enabling this feature, user have to choose the blind fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Blind Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '284',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_enable_private_fee',
			'value' => '1',
			'description' => 'On enabling this feature, user have to choose the private fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Private Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '285',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_enable_featured_fee',
			'value' => '1',
			'description' => 'On enabling this feature, user have to choose the featured fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Featured Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '286',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_contest_holder_can_choose_blind_fee',
			'value' => '1',
			'description' => 'On enabling this feature, contest holder have to choose the blind fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Contest Holder to Choose Blind Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '287',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_contest_holder_can_choose_private_fee',
			'value' => '1',
			'description' => 'On enabling this feature, contest holder have to choose the private fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Contest Holder to Choose Private Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '288',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_contest_holder_can_choose_featured_fee',
			'value' => '1',
			'description' => 'On enabling this feature, contest holder have to choose the featured fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Contest Holder to Choose Featured Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '289',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.enable_request_for_cancellation_type',
			'value' => 'Entries',
			'description' => 'The selected option will be compared with given limit required to enable request for cancellation.',
			'type' => 'select',
			'options' => 'Entries, Users, Entries or Users',
			'label' => '',
			'order' => '3',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '292',
			'setting_category_id' => '76',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_maxlife',
			'value' => '5',
			'description' => 'The maximum number of days for which a remember me session is valid; afterwards, the user will need to log in again.  Enter 0 for no expiration.',
			'type' => 'text',
			'options' => '',
			'label' => 'Days to remember the user',
			'order' => '10',
			'plugin_name' => ''
		),
		array(
			'id' => '293',
			'setting_category_id' => '76',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_maxlogins',
			'value' => '5',
			'description' => 'The maximum number of Persistent Logins remembered per user.',
			'type' => 'select',
			'options' => '5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100',
			'label' => 'Remembered logins per user',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '294',
			'setting_category_id' => '76',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_cookie_prefix',
			'value' => '360contest',
			'description' => 'A string used as prefix to build the persistent login cookie name. Characters allowed: ASCII letters ([A-Z], [a-z]), digits ([0-9]), hyphens (\"-\") or underscores (\"_\"). Previous cookies stored in user ',
			'type' => 'text',
			'options' => '',
			'label' => 'Cookie name prefix',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '295',
			'setting_category_id' => '76',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_secure',
			'value' => 'Only the listed pages',
			'description' => '',
			'type' => 'select',
			'options' => 'Every page except the listed pages, Only the listed pages',
			'label' => 'Pages which require an explicit login',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '296',
			'setting_category_id' => '76',
			'setting_category_parent_id' => '5',
			'name' => 'user.remember_me_pages',
			'value' => 'contests/add',
			'description' => 'Enter pages comma separated',
			'type' => 'textarea',
			'options' => '',
			'label' => 'Pages',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '297',
			'setting_category_id' => '30',
			'setting_category_parent_id' => '5',
			'name' => 'user.is_enable_forgot_password_captcha',
			'value' => '1',
			'description' => 'Here you can enable captcha when user request for forgot password',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Captcha when Forgot Password',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '540',
			'setting_category_id' => '29',
			'setting_category_parent_id' => '5',
			'name' => 'googleplus.is_enabled_googleplus_connect',
			'value' => '1',
			'description' => 'By enabling this feature, users can authenticate their Crowdfund account using Google+.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Google+',
			'order' => '4',
			'plugin_name' => ''
		),
		array(
			'id' => '541',
			'setting_category_id' => '77',
			'setting_category_parent_id' => '15',
			'name' => 'googleplus.consumer_secret',
			'value' => '5dUnvSsVNnLmodPW41Fjn3F5',
			'description' => 'This is the Secrete key used in Google+ share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Secret key',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '542',
			'setting_category_id' => '77',
			'setting_category_parent_id' => '15',
			'name' => 'googleplus.consumer_key',
			'value' => '1061226080208.apps.googleusercontent.com',
			'description' => 'This is the Consumer ID used in Google+ share.',
			'type' => 'text',
			'options' => '',
			'label' => 'Consumer ID',
			'order' => '2',
			'plugin_name' => ''
		),
		array(
			'id' => '543',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '2',
			'name' => 'pre_launch.bg_image',
			'value' => '',
			'description' => '(Preferred 950x552)',
			'type' => 'file',
			'options' => '',
			'label' => 'Upload Background Image',
			'order' => '6',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '544',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '2',
			'name' => 'pre_launch.bg_image_stretch_type ',
			'value' => 'Stretch',
			'description' => 'The selected option is used for handling background image.
Repeat - Tiles the image. Stretch - Stretches the image to 100% using CSS. AutoResize - Keeps the image resized to 100% of window region using JavaScript.',
			'type' => 'select',
			'options' => 'Repeat, Stretch, AutoResize',
			'label' => 'Stretch Type ',
			'order' => '5',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '546',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '2',
			'name' => 'site.launch_mode',
			'value' => 'Launched',
			'description' => 'If Pre-launch mode is selected, users/visitors will only be able to subscribe to your site. Only Administrator (that will be you) can access the site (e.g., http://yourdomain.com/admin). (Turn this on, when you want site traffic before launching the site.). If Private Beta mode is selected, only Administrator and users/visitors those who are having the invite code can sign up to your site and access the site, other can only able to request for invite code.',
			'type' => 'select',
			'options' => 'Pre-launch, Private Beta, Launch',
			'label' => 'Launch Mode',
			'order' => '1',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '547',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '2',
			'name' => 'site.private_beta_content',
			'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin blandit nisi non nisl fermentum sit amet volutpat eros tincidunt. Sed tempor blandit gravida.',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Site content for private beta mode',
			'order' => '5',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '548',
			'setting_category_id' => '78',
			'setting_category_parent_id' => '2',
			'name' => 'site.pre_launch_content',
			'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin blandit nisi non nisl fermentum sit amet volutpat eros tincidunt. Sed tempor blandit gravida.',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Site content for pre-launch mode',
			'order' => '4',
			'plugin_name' => 'LaunchModes'
		),
		array(
			'id' => '549',
			'setting_category_id' => '80',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.payment_threshold_for_threshold_limit_reach',
			'value' => '1',
			'description' => 'This is the minimum amount to be earned by an \"Affiliate User\" for placing a \"withdrawal request\".',
			'type' => 'text',
			'options' => '',
			'label' => 'Minimum Withdrawal Threshold Limit',
			'order' => '6',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '550',
			'setting_category_id' => '81',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.commission_holding_period',
			'value' => '0',
			'description' => 'This is the maximum period (in number of days) in which the commission amount will be in \"holding\" status. During this stage the user (An Affiliate) cannot place a request for the Withdrawal.',
			'type' => 'text',
			'options' => '',
			'label' => 'Maximum Commission Holding Period',
			'order' => '3',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '551',
			'setting_category_id' => '81',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.commission_on_every_pledge',
			'value' => '1',
			'description' => 'By enabling this feature, affiliate user will earn the commission amount on every pledge. (Turn this off, if you want affiliate users to be payed only for his first pledge)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Pay commission on every pledge',
			'order' => '4',
			'plugin_name' => 'Pledge'
		),
		array(
			'id' => '552',
			'setting_category_id' => '82',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.referral_cookie_expire_time',
			'value' => '1',
			'description' => 'This will be the maximum time limit within which the referral cookie has to be used (by the User), after this time gets elapsed the cookie will get expired or become unusable.',
			'type' => 'text',
			'options' => '',
			'label' => 'Referral Cookie Expire Time',
			'order' => '2',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '553',
			'setting_category_id' => '80',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.site_commission_amount',
			'value' => '1',
			'description' => 'This is the amount which will be deducted during the Affiliate cash withdrawal. (Leave blank space for \"no fee\" transaction)',
			'type' => 'text',
			'options' => '',
			'label' => 'Transaction Fee',
			'order' => '7',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '554',
			'setting_category_id' => '80',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.site_commission_type',
			'value' => 'amount',
			'description' => 'The selected option will be used as the default option for \"fee type\" during an \"Affiliate cash withdrawal\"',
			'type' => 'select',
			'options' => 'percentage,amount',
			'label' => '',
			'order' => '8',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '555',
			'setting_category_id' => '81',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.commission_on_every_contest_listing',
			'value' => '1',
			'description' => 'By enabling this feature, affiliate user will earn commission amount on every contest listing. (Turn this off, if you want affiliate users to be payed only for his first contest listing)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Pay commission on every contest listing',
			'order' => '5',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '556',
			'setting_category_id' => '81',
			'setting_category_parent_id' => '79',
			'name' => 'affiliate.affiliate.commission_on_every_contest_price',
			'value' => '1',
			'description' => 'By enabling this feature, affiliate user will earn commission amount on every contest prize. (Turn this off, if you want affiliate users to be payed only for his first contest prize)',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Pay commission on every contest prize',
			'order' => '6',
			'plugin_name' => 'Affiliates'
		),
		array(
			'id' => '557',
			'setting_category_id' => '83',
			'setting_category_parent_id' => '15',
			'name' => 'google_analytics.access_token',
			'value' => '',
			'description' => 'This will be automatically updated when \"Update Google Analytics Credentials\" link is clicked. (Required for get data from Google Analytics)',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Token',
			'order' => '5',
			'plugin_name' => 'IntegratedGoogleAnalytics'
		),
		array(
			'id' => '558',
			'setting_category_id' => '83',
			'setting_category_parent_id' => '15',
			'name' => 'google_analytics.profile_id',
			'value' => '63232568',
			'description' => 'This is the Profile ID to fetch data from Google Analytics. Please refer this <a href=\"##ANALYTICS_IMAGE##\" target=\"_blank\">image</a>. Example: p\'XXXX\'.',
			'type' => 'text',
			'options' => '',
			'label' => 'Profile ID',
			'order' => '4',
			'plugin_name' => 'IntegratedGoogleAnalytics'
		),
		array(
			'id' => '559',
			'setting_category_id' => '85',
			'setting_category_parent_id' => '84',
			'name' => 'cloudflare.token',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'CloudFlare Token',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '560',
			'setting_category_id' => '85',
			'setting_category_parent_id' => '84',
			'name' => 'cloudflare.email',
			'value' => '',
			'description' => '',
			'type' => 'Text',
			'options' => '',
			'label' => 'CloudFlare Email Id',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '561',
			'setting_category_id' => '85',
			'setting_category_parent_id' => '84',
			'name' => 'cloudflare.is_cloudflare_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable CloudFlare',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '562',
			'setting_category_id' => '86',
			'setting_category_parent_id' => '84',
			'name' => 'is_page_speed_enabled',
			'value' => '1',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '563',
			'setting_category_id' => '87',
			'setting_category_parent_id' => '84',
			'name' => 'cdn.images',
			'value' => '',
			'description' => 'This is base URL (without trailing slash) for CDN images. (e.g., http://images.yourdomain.com)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN Image URL',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '564',
			'setting_category_id' => '87',
			'setting_category_parent_id' => '84',
			'name' => 'cdn.css',
			'value' => '',
			'description' => 'This is base URL (without trailing slash) for CDN CSS. (e.g., http://css.yourdomain.com)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN CSS URL',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '565',
			'setting_category_id' => '87',
			'setting_category_parent_id' => '84',
			'name' => 'cdn.js',
			'value' => '',
			'description' => 'This is base URL (without trailing slash) for CDN JavaScript. (e.g., http://js.yourdomain.com)',
			'type' => 'text',
			'options' => '',
			'label' => 'CDN JS URL',
			'order' => '4',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '566',
			'setting_category_id' => '87',
			'setting_category_parent_id' => '84',
			'name' => 'cdn.is_cdn_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Pull CDN',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '567',
			'setting_category_id' => '88',
			'setting_category_parent_id' => '84',
			'name' => 'mail.is_smtp_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable SMTP server',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '568',
			'setting_category_id' => '88',
			'setting_category_parent_id' => '84',
			'name' => 'mail.smtp_host',
			'value' => '',
			'description' => 'Add like ssl://smtp.gmail.com <http://smtp.gmail.com> host name',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP host',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '569',
			'setting_category_id' => '88',
			'setting_category_parent_id' => '84',
			'name' => 'mail.mail.smtp_port',
			'value' => '465',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP port',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '570',
			'setting_category_id' => '88',
			'setting_category_parent_id' => '84',
			'name' => 'mail.smtp_username',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP username',
			'order' => '4',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '571',
			'setting_category_id' => '88',
			'setting_category_parent_id' => '84',
			'name' => 'mail.smtp_password',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'SMTP password',
			'order' => '5',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '572',
			'setting_category_id' => '89',
			'setting_category_parent_id' => '84',
			'name' => 'RedisSession.is_redis_session_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Redis',
			'order' => '7',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '573',
			'setting_category_id' => '89',
			'setting_category_parent_id' => '84',
			'name' => 'RedisSession.hostname',
			'value' => '192.168.1.7',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => 'Redis Host Name',
			'order' => '8',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '574',
			'setting_category_id' => '89',
			'setting_category_parent_id' => '84',
			'name' => 'RedisSession.port',
			'value' => '1377',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => 'Redis Port',
			'order' => '9',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '575',
			'setting_category_id' => '90',
			'setting_category_parent_id' => '84',
			'name' => 'Memcached.is_memcached_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Memcached',
			'order' => '1',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '576',
			'setting_category_id' => '90',
			'setting_category_parent_id' => '84',
			'name' => 'Memcached.servers',
			'value' => '192.168.1.7',
			'description' => 'Add multiple server host name (seperated by comma)',
			'type' => 'text',
			'options' => '',
			'label' => 'Memcached Servers',
			'order' => '2',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '577',
			'setting_category_id' => '91',
			'setting_category_parent_id' => '84',
			'name' => 'HtmlCache.is_htmlcache_enabled',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Full-page Caching',
			'order' => '3',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '578',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.is_enabled',
			'value' => '0',
			'description' => 'Uncheck this to revert back to using your own web host for storage and delivery at anytime',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable storing of files to Amazon S3 and serving files from Amazon S3',
			'order' => '10',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '594',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.end_point',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'End Point',
			'order' => '15',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '580',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.aws_access_key',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Access Key',
			'order' => '12',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '581',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.aws_secret_key',
			'value' => '',
			'description' => '',
			'type' => 'text',
			'options' => '',
			'label' => 'Secret Key',
			'order' => '13',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '582',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.bucket_name',
			'value' => '',
			'description' => '##TEST_CONNECTION##',
			'type' => 'text',
			'options' => '',
			'label' => 'Bucket Name',
			'order' => '14',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '583',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.keep_copy_in_local',
			'value' => '0',
			'description' => '',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Keep copy in local',
			'order' => '15',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '584',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.is_cname_enabled',
			'value' => '0',
			'description' => 'For more details please refer <a title=\"For more info\" target=\"_blank\" href=\"http://docs.amazonwebservices.com/AmazonS3/2006-03-01/VirtualHosting.html\">http://docs.amazonwebservices.com/AmazonS3/2006-03-01/VirtualHosting.html</a>',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Bucket is setup for virtual hosting',
			'order' => '16',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '585',
			'setting_category_id' => '92',
			'setting_category_parent_id' => '84',
			'name' => 's3.upload_static_content_enabled',
			'value' => '0',
			'description' => 'Static content such as CSS, JavaScript, images files in <code>webroot</code> folder. Uncheck this to revert back to using own server for delivery at anytime.',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable to deliver all the static contents from Amazon S3',
			'order' => '17',
			'plugin_name' => 'HighPerformance'
		),
		array(
			'id' => '586',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_enable_highlight_fee',
			'value' => '1',
			'description' => 'On enabling this feature, user have to choose the highlight fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Highlight Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '587',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contest.is_contest_holder_can_choose_highlight_fee',
			'value' => '1',
			'description' => 'On enabling this feature, contest holder have to choose the highlight fee when posting the contest',
			'type' => 'checkbox',
			'options' => '',
			'label' => 'Enable Contest Holder can set Highlight Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '588',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '9',
			'name' => 'contest.upgrade_fee_payer',
			'value' => 'User',
			'description' => '',
			'type' => 'radio',
			'options' => 'User,Site',
			'label' => 'Who will pay the gateway fee for contest upgrade',
			'order' => '3',
			'plugin_name' => 'Contest'
		),
		array(
			'id' => '589',
			'setting_category_id' => '94',
			'setting_category_parent_id' => '9',
			'name' => 'contest.extend_time_fee_payer',
			'value' => 'User',
			'description' => '',
			'type' => 'radio',
			'options' => 'User,Site',
			'label' => 'Who will pay the gateway fee for contest upgrade',
			'order' => '4',
			'plugin_name' => 'Contest'
		),
		array(
			'id' => '590',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.browse_thumb.width',
			'value' => '70',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '591',
			'setting_category_id' => '0',
			'setting_category_parent_id' => '0',
			'name' => 'thumb_size.browse_thumb.height',
			'value' => '70',
			'description' => '',
			'type' => '',
			'options' => '',
			'label' => '',
			'order' => '0',
			'plugin_name' => ''
		),
		array(
			'id' => '592',
			'setting_category_id' => '57',
			'setting_category_parent_id' => '8',
			'name' => 'contest.highlight_fee',
			'value' => '70',
			'description' => 'This is highlight fee for the contest. It can be overridden per contest type.',
			'type' => 'text',
			'options' => '',
			'label' => 'Highlight Fee',
			'order' => '0',
			'plugin_name' => 'Contests'
		),
		array(
			'id' => '593',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contestuser.video.allowedSize',
			'value' => '9',
			'description' => 'By changing this value entry video size allowed will changed.',
			'type' => 'text',
			'options' => '',
			'label' => 'Entry Video size',
			'order' => '0',
			'plugin_name' => 'VideoResources'
		),
		array(
			'id' => '595',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contestuser.audio.allowedSize',
			'value' => '9',
			'description' => 'By changing this value entry audio size allowed will changed.',
			'type' => 'text',
			'options' => '',
			'label' => 'Audio Video size',
			'order' => '0',
			'plugin_name' => 'AudioResources'
		),
		array(
			'id' => '596',
			'setting_category_id' => '52',
			'setting_category_parent_id' => '8',
			'name' => 'contestuser.text.allowedSize',
			'value' => '9',
			'description' => 'By changing this value entry text size allowed will changed.',
			'type' => 'text',
			'options' => '',
			'label' => 'Entry Text size',
			'order' => '0',
			'plugin_name' => 'TextResources'
		),
	);

}
