<?php
/**
 * 360Contest
 *
 * PHP version 5
 *
 * @category   PHP
 * @package    360Contest
 * @subpackage Core
 * @author     Agriya <info@agriya.com>
 * @copyright  2018 Agriya Infoway Private Ltd
 * @license    http://www.agriya.com/ Agriya Infoway Licence
 * @link       http://www.agriya.com
 */
class UserData {

	public $table = 'users';

	public $records = array(
		array(
			'id' => '1',
			'role_id' => '1',
			'username' => 'admin',
			'password' => '$1$jeZk_`04$IUoPXnw2ETrHF89iu83Qw1',
			'name' => 'Administrator',
			'email' => 'productdemo.admin@gmail.com',
			'available_wallet_amount' => '0.00',
			'commission_paid_amount' => '0.00',
			'total_amount_withdrawn' => '90.00',
			'website' => '/about',
			'image' => '',
			'bio' => '',
			'timezone' => '0',
			'created' => '2009-04-05 00:20:34',
			'modified' => '0000-00-00 00:00:00',
			'contest_count' => '0',
			'contest_user_count' => '0',
			'contest_user_own_count' => '0',
			'total_amount_deposited' => '0.00',
			'total_site_revenue_as_participant' => '0.00',
			'participant_total_earned_amount' => '0.00',
			'contest_user_won_count' => '0',
			'contest_files_expectation_count' => '0',
			'contest_user_eliminated_count' => '0',
			'contest_user_withdrawn_count' => '0',
			'contest_user_active_count' => '0',
			'contest_user_lost_count' => '0',
			'total_site_revenue_as_contest_holder' => '260.00',
			'contest_payment_pending_count' => '1',
			'contest_pending_approval_count' => '0',
			'contest_open_count' => '0',
			'contest_rejected_count' => '0',
			'contest_request_for_cancellation_count' => '0',
			'contest_canceled_by_admin_count' => '0',
			'contest_judging_count' => '5',
			'contest_pending_action_to_admin_count' => '0',
			'contest_winner_selected_count' => '0',
			'contest_winner_selected_by_admin_count' => '2',
			'contest_change_requested_count' => '0',
			'contest_change_completed_count' => '0',
			'contest_expecting_deliverables_count' => '0',
			'contest_completed_count' => '0',
			'contest_paid_to_participant_count' => '1',
			'contest_request_for_refund_count' => '0',
			'contest_expired_count' => '0',
			'user_openid_count' => '0',
			'user_login_count' => '0',
			'user_view_count' => '0',
			'contest_follower_count' => '0',
			'total_withdraw_request_count' => '1',
			'total_ratings' => '13',
			'rating_count' => '3',
			'average_rating' => '0.00',
			'blocked_amount' => '0.00',
			'available_balance_amount' => '0.00',
			'is_paid' => '1',
			'is_email_confirmed' => '1',
			'is_active' => '1',
			'is_agree_terms_conditions' => '',
			'is_openid_register' => '',
			'is_facebook_register' => '',
			'is_twitter_register' => '',
			'is_google_register' => '',
			'is_yahoo_register' => '',
			'is_linkedin_register' => '',
			'is_affiliate_user' => '',
			'facebook_user_id' => '0',
			'facebook_access_token' => '0',
			'twitter_user_id' => '',
			'twitter_access_key' => '',
			'twitter_access_token' => '',
			'twitter_avatar_url' => '',
			'google_user_id' => '',
			'google_access_token' => '',
			'googleplus_user_id' => '',
			'is_googleplus_register' => '0',
			'is_googleplus_connected' => '',
			'googleplus_contacts_count' => '0',
			'googleplus_avatar_url' => '',
			'yahoo_user_id' => '',
			'yahoo_access_token' => '',
			'linkedin_user_id' => '',
			'linkedin_access_token' => '',
			'linkedin_avatar_url' => '',
			'openid_user_id' => '',
			'is_facebook_connected' => '',
			'is_twitter_connected' => '',
			'is_google_connected' => '',
			'is_yahoo_connected' => '',
			'is_linkedin_connected' => '',
			'cookie_hash' => '',
			'cookie_time_modified' => '0000-00-00 00:00:00',
			'signup_ip_id' => '',
			'last_login_ip_id' => '0',
			'last_logged_in_time' => '0000-00-00 00:00:00',
			'mobile_app_time_modified' => '',
			'iphone_last_request' => '0000-00-00 00:00:00',
			'iphone_latitude' => '',
			'iphone_longitude' => '',
			'mobile_app_hash' => '',
			'iphone_last_access' => '',
			'fb_friends_count' => '0',
			'twitter_followers_count' => '0',
			'linkedin_contacts_count' => '0',
			'google_contacts_count' => '0',
			'yahoo_contacts_count' => '0',
			'is_skipped_fb' => '1',
			'is_skipped_twitter' => '1',
			'is_skipped_google' => '1',
			'is_skipped_yahoo' => '1',
			'is_skipped_linkedin' => '1',
			'user_avatar_source_id' => '1',
			'referred_by_user_id' => '0',
			'referred_by_user_count' => '0',
			'referred_contest_count' => '0',
			'total_commission_pending_amount' => '0.00',
			'total_commission_canceled_amount' => '0.00',
			'total_commission_completed_amount' => '0.00',
			'commission_line_amount' => '0.00',
			'commission_withdraw_request_amount' => '0.00',
			'pwd_reset_token' => '',
			'pwd_reset_requested_date' => '0000-00-00 00:00:00',
			'is_idle' => '1',
			'is_contest_posted' => '',
			'is_entry_posted' => '',
			'is_engaged' => '',
			'site_state_id' => '0',
			'sudopay_gateway_id' => '0',
			'sudopay_receiver_account_id' => '0',
			'sudopay_revised_amount' => '0.00',
			'sudopay_token' => '',
			'invite_count' => '0',
			'activity_message_id' => '0',
			'security_question_id' => '0',
			'security_answer' => ''
		),
	);

}
